### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by volkus1893** [lorbetzki/net.lorbetzki.zoe#1]
Hi, after installing and on first run I get this error:
Notice: Undefined index: accounts in C:\ProgramData\Symcon\modules\.store\net.lorbetzki.zoe\libs\functions.php on line 91

Notice: Trying to access array offset on value of type null in C:\ProgramData\Symcon\modules\.store\net.lorbetzki.zoe\libs\functions.php on line 91

Notice: Trying to access array offset on value of type null in C:\ProgramData\Symcon\modules\.store\net.lorbetzki.zoe\libs\functions.php on line 91

I entered user and pw before that.
Did I do anything wrong or are there some changes at renault?
Volker

**Comment by lorbetzki** [comment]
Hi,

renault updated the Kameron API Key, please use the Beta version on the Symcon store, the new key is implemented.

**Comment by volkus1893** [comment]
Yes, that works - thank you. Great Module !!!!
